### ISSUE TITLE
Tenant Aware

### ISSUE THREAD

**Issue by ramaID** [laravolt/camunda#17]
https://tenancy.dev/docs/hyn/5.6/queues

Kita perlu melempar parameter `website_id` ketika dispatch sebuah `job`.

**Comment by ramaID** [comment]
Bagaimana cara / workaround untuk menambahkan parameter tersebut?

https://github.com/laravolt/camunda/blob/2c47ca1be7e629d3cce65a1b0f718d7ab563c824/src/Commands/ConsumeExternalTaskCommand.php#L34

**Comment by uyab** [comment]
@ramaID bisa kasih contoh cara pemanggilan Job biar tenant aware?

```php
SomeJob::dispatch($workerId, $task, $websiteId);

vs

$job = new SomeJob($workerId, $task, $websiteId);
$job->dispatch()

```

Dua contoh di atas valid semua?

**Comment by ramaID** [comment]
problem lainnya, karena pintu masuknya job tersebut dari `scheduler`, kemungkinan kita tidak bisa memakai scheduler untuk melempar parameter tersebut. apakah memungkinkan `consume-external-task` melalui dispatch dari kode aplikasi? misalnya dari service class, `app/Services/Bpmn/Pengaduan/PengaduanService.php`

**Comment by ramaID** [comment]
> @ramaID bisa kasih contoh cara pemanggilan Job biar tenant aware?
> 
> ```
> SomeJob::dispatch($workerId, $task, $websiteId);
> 
> vs
> 
> $job = new SomeJob($workerId, $task, $websiteId);
> $job->dispatch()
> ```
> 
> Dua contoh di atas valid semua?

Tidak valid, karena parameter harusnya `website_id`

**Comment by ramaID** [comment]
![Screenshot 2023-06-28 at 10 07 34](https://github.com/laravolt/camunda/assets/34129273/3be48e97-4220-4c37-a5d3-694b515b267e)

sumber: https://tenancy.dev/docs/hyn/5.6/queues

letak parameter `website_id` tidak akan jadi masalah

**Comment by uyab** [comment]
ooh, ini yang penting property $website_id diset ya, ga peduli gimana caranya.
